name: Build and Deploy Docs

on:
  push:
    branches: [devel]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install doc tools
        run: |
          pip install sphinx myst-parser sphinx_rtd_theme 

    #   - name: Build libaries
    #     run: |
    #       sudo apt install cmake build-essential gfortran liblapack-dev liblapacke-dev 
    #       wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
    #       tar -xvf eigen-3.4.0.tar.gz
    #       pip install pybind11-global
    #       mkdir -p build
    #       cd build 
    #       cmake .. -DCXX=g++ -DFC=gfortran -DEIGEN_INC=./eigen-3.4.0/  -DBUILD_LIBS=ON  -DPython3_EXECUTABLE=`which python`
    #       make -j4 
    #       make install
    #       cd ..
          
          
    #   - name: Build Doxygen C++ API Docs
    #     run: doxygen misc/doxygen/doxygen.cfg 

    #   - name: Build Python docs (Sphinx)
    #     run: |
    #       sphinx-apidoc -o misc/source/python ./specd
          
      - name: Build master docs (Sphinx)
        run: |
          sphinx-build -b html misc/source docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs